development: &default
  adapter: postgresql
  database: readingcodegood_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: readingcodegood_test

production:
  <<: *default
  database: readingcodegood_staging

production:
  <<: *default
  database: readingcodegood_staging
